plugins {
    id 'com.android.application'
}

android {
    namespace 'com.workstep.android'
    compileSdk 35

    defaultConfig {
        applicationId 'com.workstep.android'
        minSdk 29
        targetSdk 35
        versionCode 12
        versionName '1.0.11'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
